### ISSUE TITLE
[BE]3차 리뷰 반영(codesquad-members-2022/issue-tracker#153)

### ISSUE THREAD

**Issue by mybloom** [bugpigg/issue-tracker#37]
### 📙 작업 내역

- 이슈 API
	- [x] 	파라미터 검증부분을 사용하는 부분에서 하도록 변경 . 현재는 검증은 controller에서 하고 사용은 service에서 한다.
	- [x] ServiceDto 삭제
	- [x] 학습 test 삭제

- 로그인 API
  - [x] 인터셉터를 활용하여 로그인 검증 과정 수정하기

### 📘 작업 유형

- 리펙토링

### 📝 Issue 특이 사항

<br/><br/>
