### ISSUE TITLE
[BE]5차 리뷰 반영 (codesquad-members-2022/issue-tracker#261)

### ISSUE THREAD

**Issue by mybloom** [bugpigg/issue-tracker#49]
### 📙 작업 내역

- [ ] 4차 리뷰에 반영한 코드 전반 리팩토링에 대한 2차 리팩토링
- [ ] 연관관계 편의 메서드 부분 
- [x] 이슈 검색 관련 수정 사항 반영

### 📘 작업 유형

- 리펙토링

### 📝 Issue 특이 사항

<br/><br/>
